version: '3.8'

networks:
  gl-oauth:
    name: gl-oauth

volumes:
  gl-oauth-pgsql:
  gl-oauth-redis:

services:
  gl-oauth.api:
    build:
      context: ./
      dockerfile: src/OauthShowcase/Dockerfile
    restart: unless-stopped
    depends_on: 
      - gl-oauth.postgres
    ports:
      - "${API_HOST:-127.0.0.1}:${APP_PORT}:80"
    networks:
      - gl-oauth
    env_file:
      - .env

  gl-oauth.postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${PG_DB:-gl-oauth_db}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASS}"
      PGDATA: "/var/lib/pgsql/data"
    volumes:
      - gl-oauth-pgsql:/var/lib/pgsql/data
    ports:
      - "${POSTGRES_HOST:-127.0.0.1}:${POSTGRES_PORT}:5432"
    networks:
      - gl-oauth
    env_file:
      - .env

